"""
Django settings for orga project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = "/static/"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-qw=sxp!83ajud&+b-hqro1vg__8*t$_kwj)xgj700#mq7e^ga-')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ and 'VERCEL' not in os.environ

ALLOWED_HOSTS = ['.vercel.app', '.now.sh', '127.0.0.1', 'localhost']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Necessario per Vercel (permette il login e i form POST)
CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'menu',
    'pwa',
]

JAZZMIN_SETTINGS = {
    "site_title": "Orga Admin",
    "site_header": "Orga Dashboard",
    "site_brand": "Grotesque",
    "site_logo": "images/logo-login.png",  # Percorso del logo
    "login_logo": "images/logo.png",
    "welcome_sign": "Benvenuto in Orga!",
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": ["auth"],
    "theme": "darkly",
    "show_ui_builder": True,
    "order_with_respect_to": ["menu.Menu", "menu.Categoria", "menu.Piatto", "menu.Allergene"],
    "icons": {
        "menu.Piatto": "fas fa-utensils",
        "menu.Menu": "fas fa-book-open",
        "menu.Categoria": "fas fa-tags", 
        "menu.Allergene": "fas fa-exclamation-triangle",
    },
    # Link rapidi nella barra in alto
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Nuovo Menu", "url": "admin:menu_menu_add"},
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'orga.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'menu', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'orga.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

IS_PRODUCTION = 'VERCEL' in os.environ or 'RENDER' in os.environ

if IS_PRODUCTION:
    if 'DATABASE_URL' not in os.environ:
        raise ImproperlyConfigured("La variabile d'ambiente DATABASE_URL non è impostata nell'ambiente di produzione.")
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configurazione Redirect Login/Logout
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGES = [
    ('it', 'Italian'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

LANGUAGE_CODE = 'it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Cartella dove collectstatic raccoglierà i file per la produzione
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Abilita la compressione e il caching dei file statici con WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- PWA CONFIGURATION ---
PWA_APP_NAME = 'Orga Menu'
PWA_APP_DESCRIPTION = "Il menu digitale del tuo ristorante"
PWA_APP_THEME_COLOR = '#343a40'  # Colore della barra di stato (es. scuro come Jazzmin)
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_START_URL = '/'
PWA_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/logo_1.png',  # Assicurati di avere questo file!
        'sizes': '192x192'
    },
    {
        'src': '/static/images/logo_1.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [{'src': '/static/images/logo_1.png', 'sizes': '512x512'}]
PWA_APP_LANG = 'it-IT'
