# Generated by Django 5.1.6 on 2025-03-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Cereali contenenti glutine'), (2, 'Crostacei'), (3, 'Uova'), (4, 'Pesce'), (5, 'Arachidi'), (6, 'Soia'), (7, 'Latte'), (8, 'Frutta a guscio'), (9, 'Sedano'), (10, 'Senape'), (11, 'Semi di sesamo'), (12, 'Anidride solforosa e solfiti'), (13, 'Lupini'), (14, 'Molluschi')], unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Allergene',
                'verbose_name_plural': 'Allergeni',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('allergeni', models.ManyToManyField(blank=True, to='menu.allergene')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piatti', to='menu.categoria')),
            ],
            options={
                'verbose_name': 'Piatto',
                'verbose_name_plural': 'Piatti',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_creazione', models.DateField(auto_now_add=True)),
                ('piatti', models.ManyToManyField(to='menu.piatto')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
