# Generated by Django 5.1.6 on 2026-01-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='note_interne',
            field=models.TextField(blank=True, help_text='Note visibili solo allo staff (es. dettagli evento, tavolo, ecc.)', null=True, verbose_name='Note Interne'),
        ),
    ]
